### PR TITLE
Fixes #99: Add support for Foscam F19803P camera

### LINKED ISSUE #99: Add support for Foscam F19803P camera
As stated here: https://www.soleratec.com/support/rtsp/rtsp_listing?camera_company=Foscam&camera_model=FI9803P

The RTSP URL is: `rtsp://{{username}}:{{password}}@{{ip_address}}/11`

The OUI (from customer) is: `E8:AB:FA`

### PR DESCRIPTION
**Pull request by jhallard**

### CODE REVIEW

**Review by jcmaslan — COMMENTED** [review]
Please see overlap with techview entry below that may just be missing stream choices for 12 vs 11 suffix of RTSP url.

**Comment by jhallard** [comment]
Wow good catch, thanks for seeing that. I haven't seen any literature describing the semantics of the 11 vs 12, is it a good idea to just flatten those entries into one with a 1 and 2 stream?

**Comment by jhallard** [comment]
Interestingly, the user reports that they were only able to connect using the /videoMain RTSP Path, the same as exists for the current Foscam entries. I guess the website I found was wrong, will update.

**Comment by jcmaslan** [comment]
Yes, flatten to avoid their being mutually exclusive in way we support of
them.

**Comment by jhallard** [comment]
Code is changed, removed the entry and just added the OUI to the existing Foscam entry since user confirmed (with VLC) that /videoMain is the correct RTSP Path.

**Comment by jhallard** [comment]
customer is waiting on support so I'm going to merge this now that they've confirmed the rtsp URL

**Review by jcmaslan — COMMENTED** [review]
LGTM

**Pull request merged**
