### PR TITLE
Fixed #95: Add Support for Alptop AT-LIR400 camera

### LINKED ISSUE #95: Add Alptop AT-LIR400 camera
OUI:
```
00:00:1B
```

maker:
```
Alptop
```

model:
```
AT-LIR400
```

manual is http://www.alptopsecurity.com/16.html

Server:
rtsp://{{username}}:{{password}}@{{ip_address}}:{{port}}

Path:
/{{stream}}

port is `554`
stream is `0`

### PR DESCRIPTION
**Pull request by jhallard**

### CODE REVIEW

**Comment by jcmaslan** [comment]
Confirmed works with customer

**Review by jcmaslan — APPROVED** [review]
LGTM. confirmed with customer.

**Comment by jhallard** [comment]
but do we want to add in a second stream option?

**Comment by jcmaslan** [comment]
2nd stream not yet confirmed

**Comment by jhallard** [comment]
Okay should I go ahead and merge/deploy this until we confirm second stream is available?

**Comment by jhallard** [comment]
deployed

**Pull request merged**
