### PR TITLE
Fixes #133: Add support for Uniview NVR380-64R NVR

### LINKED ISSUE #133: Add support for Uniview NVR308-64R
User Manual is here: 

They don't seem to explicitly list the RTSP connection information, and looking on Google doesn't show any meaningful results, but tucked away in the user manul is this image

image

which seems to suggest that the RTSP URL is

`rtsp://{{username}}:{{password}}@{{ip_address}}:{{port}}/unicast/c{{channel}}/s{{stream}}/live`

where channel is `1-n` and stream is 0 for main and 1 for sub. I'll get this added and test it out with our customer.

### PR DESCRIPTION
**Pull request by jhallard**

### CODE REVIEW

**Review by jcmaslan — CHANGES_REQUESTED** [review]
One too many channels

**Comment by jhallard** [comment]
1-16 = 16 channels? Isn't that correct? (user manual states channels are `1-n`)

**Review by jcmaslan — APPROVED** [review]
LGTM

**Comment by jhallard** [comment]
you have to actually hit 'approve', even though you say LGTM the PR is still locked.

**Comment by jhallard** [comment]
there we go

**Comment by jhallard** [comment]
This has been deployed to testing and production.

**Pull request merged**
